defaults:
  - models: 2G-GCN
  - data: cad120 #mphoi, cad120, bimanual
hydra:
  run:
    dir: outputs/${data.name}/${metadata.model_name}/${logging.checkpoint_name}
resources:
  use_gpu: true
  num_threads: 32
